name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  lint:
    name: YAML Validation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run yaml:lint
      - run: npm run yaml:validate
